package visao;

import dao.produto.ProdutoDAO;
import dao.produto.ProdutoDAOMySQL;
import modelo.Produto;

public class FrmCadastroProduto extends javax.swing.JFrame {

    public FrmCadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFPrecoVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFPrecoCusto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFUnidade = new javax.swing.JTextField();
        JBTSair = new javax.swing.JButton();
        JBTLimpar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        JBTAlterar = new javax.swing.JButton();
        JBTListar = new javax.swing.JButton();
        jTFCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Dados de Produto");

        jLabel2.setText("Nome:");

        jTFNome.setName("JTFNome"); // NOI18N

        jTFPrecoVenda.setName("JTFNome"); // NOI18N

        jLabel3.setText("Preço Venda:");

        jLabel4.setText("Preço Custo:");

        jTFPrecoCusto.setName("JTFNome"); // NOI18N

        jLabel5.setText("Unidade:");

        jTFUnidade.setName("JTFNome"); // NOI18N

        JBTSair.setText("Sair");
        JBTSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTSairActionPerformed(evt);
            }
        });

        JBTLimpar.setText("Limpar");
        JBTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTLimparActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTSalvarActionPerformed(evt);
            }
        });

        jBTExcluir.setText("Excluir");
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTExcluirActionPerformed(evt);
            }
        });

        JBTAlterar.setText("Alterar");
        JBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTAlterarActionPerformed(evt);
            }
        });

        JBTListar.setText("Listar");
        JBTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTListarActionPerformed(evt);
            }
        });

        jTFCategoria.setName("JTFNome"); // NOI18N

        jLabel7.setText("Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFPrecoCusto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jTFUnidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBTAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTListar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBTAlterar, JBTLimpar, JBTListar, JBTSair, jBTExcluir, jBTSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBTSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTListar)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTFPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTSairActionPerformed

    private void JBTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTLimparActionPerformed
        jTFNome.setText("");
        jTFPrecoVenda.setText("");
        jTFPrecoCusto.setText("");
        jTFUnidade.setText("");
        jTFCategoria.setText("");
    }//GEN-LAST:event_JBTLimparActionPerformed

    private void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        if (!jTFNome.getText().equals("")) {
            Produto produto = new Produto();
            if (produtoId != -1) {
                produto.setProdutoId(produtoId);
            }
            produto.setNome(jTFNome.getText());
            produto.setPrecoVenda(jTFPrecoVenda.getText());
            produto.setPrecoCusto(jTFPrecoCusto.getText());
            produto.setUnidade(jTFUnidade.getText());
            produto.setCategoria(jTFCategoria.getText());
            ProdutoDAO produtodao = new ProdutoDAOMySQL();
            if (produtodao.salvar(produto)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Produto cadastrado com suscesso!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Produto não cadastrado!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "O Nome deve ser preenchido!");
            jTFNome.requestFocus();
        }
    }//GEN-LAST:event_jBTSalvarActionPerformed

    private void JBTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTListarActionPerformed
        //this.setVisible(false);
        new FrmProdutoListar().setVisible(true);
    }//GEN-LAST:event_JBTListarActionPerformed

    private void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser excluído");
        ProdutoDAO produtodao = new ProdutoDAOMySQL();
        Produto produto = produtodao.consultarPK(id);
        if (produto != null) {
            jTFNome.setText(produto.getNome());
            jTFPrecoVenda.setText(produto.getPrecoVenda());
            jTFPrecoCusto.setText(produto.getPrecoCusto());
            jTFUnidade.setText(produto.getUnidade());
            jTFCategoria.setText(produto.getCategoria());

            Object[] opcoes = {"Sim", "Não"};
            int resposta = javax.swing.JOptionPane.showOptionDialog(null, "Confirma a exclusão do Produto?", "Exclusão", 0, javax.swing.JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
            if (resposta == 0) {
                if (produtodao.apagarPK(Integer.parseInt(id))) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Produto excluído com suscesso!");
                    jTFNome.setText("");
                    jTFPrecoVenda.setText("");
                    jTFPrecoCusto.setText("");
                    jTFUnidade.setText("");
                    jTFCategoria.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Produto não excluído!");
                }
            }
        }
    }//GEN-LAST:event_jBTExcluirActionPerformed

    private void JBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTAlterarActionPerformed
        String id = javax.swing.JOptionPane.showInputDialog("Digite o id a ser alterado");
        ProdutoDAO produtodao = new ProdutoDAOMySQL();
        Produto produto = produtodao.consultarPK(id);
        if (produto != null) {
            produtoId = produto.getProdutoId();
            jTFNome.setText(produto.getNome());
            jTFPrecoVenda.setText(produto.getPrecoVenda());
            jTFPrecoCusto.setText(produto.getPrecoCusto());
            jTFUnidade.setText(produto.getUnidade());
            jTFCategoria.setText(produto.getCategoria());
        }
    }//GEN-LAST:event_JBTAlterarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroProduto().setVisible(true);
            }
        });
    }
    private int produtoId = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTAlterar;
    private javax.swing.JButton JBTLimpar;
    private javax.swing.JButton JBTListar;
    private javax.swing.JButton JBTSair;
    private javax.swing.JButton jBTExcluir;
    private javax.swing.JButton jBTSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFCategoria;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPrecoCusto;
    private javax.swing.JTextField jTFPrecoVenda;
    private javax.swing.JTextField jTFUnidade;
    // End of variables declaration//GEN-END:variables
}
